language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
sudo: false # use container-based infrastructure (pre-requisite for caching)
install:
  - pip install -e .[dev]
  - pip install coveralls

script:
  coverage run --source=clusterjob py.test --doctest-modules clusterjob tests

after_success:
  - coveralls
